### ISSUE TITLE
hi guys , i cant use heroku , then i use usually way ( clone project with git ) and after than , i change .env configuration and Run this Command in Terminal . {{ php artisan migrate:refresh --seed --force }} and i get this Mysql Error , can anyone help me , im new in laravel 

### ISSUE THREAD

**Issue by parisaaaaaa** [luckyrabbitllc/StartupEngine#11]

**Comment by parisaaaaaa** [comment]
The Error => In Connection.php line 664
( SQLSTATE[42000] ) 
Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corre
  sponds to your MySQL server version for the right syntax to use near 'json null' at line 1 (SQL: alter table `pages` add
  `json` json null)

And also 

(In Connection.php line 452)
SQLSTATE[42000]

Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corre
  sponds to your MySQL server version for the right syntax to use near 'json null' at line 1

**Comment by luckyrabbitllc** [comment]
The issue is that you must use a PostgreSQL database, not MySQL, because MySQL has limited support for the JSON column type.
