### ISSUE TITLE
how to install ???

### ISSUE THREAD

**Issue by jodumont** [luckyrabbitllc/StartupEngine#13]
Hi;

i'm sure your project is awesome but I just don't get how to install it

**Comment by luckyrabbitllc** [comment]
Hi @jodumont,

how are you planning to install it? Locally or on Heroku?

**Comment by gnerdmaster** [comment]
hello, I like install it too, but locally

**Comment by cezavaletal** [comment]
me gustaría instalarlo a nivel local, ayuda

**Comment by luckyrabbitllc** [comment]
@cezavaletal Follow the default Laravel installation instructions, then the instructions in the Startup Engine readme.

https://laravel.com/docs/5.6/installation
https://github.com/luckyrabbitllc/StartupEngine/blob/master/readme.md#deploying
