### ISSUE TITLE
Error Herokuapp build

### ISSUE THREAD

**Issue by zikwal** [luckyrabbitllc/StartupEngine#9]
Hi.
1 - please create demo account like demo@demo.com / demo1234
2 - Heroku build crashes. 

       Command Cancelled!
       > @php artisan command:SyncGit default
       Cloning into 'resources/temp'...
       
       In SyncGit.php line 70:
                                                                                      
         file_get_contents(/tmp/build_187c30ee0b96ff7009bd2f26865b447c/zikwal-Startu  
         pEngine-beb29d5/resources/views/theme/startup.json): failed to open stream:  
          No such file or directory                                                   
                                                                                      
       
       Script @php artisan command:SyncGit default handling the post-install-cmd event returned with error code 1
 !     Push rejected, failed to compile PHP app.
 !     Push failed

**Comment by luckyrabbitllc** [comment]
Hey there, thanks for checking out Startup Engine. 

There's a demo account already. (It's at the bottom of the readme)
The e-mail is **admin@example.com** and the password is **password**.

I think you may have been deploying when I was debugging Heroku's compatibility with the new functionality in the SyncGit command earlier. I just deployed and was able to build.  Try giving it another shot.  

The code is still changing daily right now, but I'm thinking it should be stable by the end of the month.
